### ISSUE TITLE
Developer content

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#106]
- [ ] Incentivized testnet communication (depending on timelies)
- [ ] Access control use case + IPFS linkage (James + can)

**Comment by cankisagun** [comment]
Mid-week update:
@torenigma to work with Outlier

**Comment by ainsleys** [comment]
working on forum post for dev-x update now. Covid-related work complete.

**Comment by ainsleys** [comment]
Completed 3/30/20: 
- [x] Covid blog post (Tor)
- [x] Covid forum post for dev call to actions (Ainsley)
- [x] Governance change blogpost (on James)
- [x] Governance decisions overview on forum (on James)

**Comment by cankisagun** [comment]
Completed 4/13/20
- [x] Outlier post (on outlier) - blog
- [x] March developer update (based on weekly updates)

**Comment by cankisagun** [comment]
Completed 4/24/20
- [ ] Overview of CosmWasm research (2nd week) - forum
- [ ] SafeTrace update (blog)

**Comment by cankisagun** [comment]
closing this issue as it s a repeating task
