### ISSUE TITLE
Getting Started with cosmwasm

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/SecretNetwork#107]
We're working on a comparison / walkthrough for cosmwasm for developers. We'll look both at how it compares to dev ex of enigma discovery and ethereum. Effort being led by @lauraweindorf and @levackt, working document here: https://github.com/lauraweindorf/enigma-dev-x

**Comment by cankisagun** [comment]
let's try to create a status update doc by the end of the week to share on the forum

**Comment by ainsleys** [comment]
Update from @levackt and @lauraweindorf : 

So far things are coming along, additional docs and CLI from Cosmos have been helpful. 

Before we can make a streamlined walkthru, we need to finish:
- [ ] a startup script that will set up a local devnet (working with the enigma testnet is maybe too unstable for now)
- [ ] limited front-end that instantiates the contract

We should expect to see a PR from @levackt here: https://github.com/lauraweindorf/enigma-dev-x
shortly, which documents his experience using the cosmwasm cli (@lauraweindorf ran into some issues getting it going). 

We'll check in early next week on the two above outstanding tasks, but I think we can share the working repo above and see if anyone is interested in following along / providing additional feedback.

**Comment by ainsleys** [comment]
Update: @levackt making progress. Will write a forum post detailing work to date to be posted EOW, as well as discuss timeline for publishing a cleaner guide.
