### ISSUE TITLE
Fix buffer limit of 2000 bytes in CosmWasm

### ISSUE THREAD

**Issue by assafmo** [enigmampc/SecretNetwork#126]
- [x] Adjust `go-cosmwasm` rust-to-go FFI to allow arbitrary-length buffers (Related to: https://github.com/CosmWasm/go-cosmwasm/issues/55)
  - This is being fixed in PR https://github.com/CosmWasm/go-cosmwasm/pull/67.
  - While working on this @reuvenpo identified and fixed many memory bugs. These are listed in the description of the PR.
  - [This comment](https://github.com/CosmWasm/go-cosmwasm/issues/66#issuecomment-617623216) in their issue tracker describes future improvements to make buffer-passing more efficient (today there are 2 copies done in each direction, where only 1 is needed)
  - [This issue](https://github.com/CosmWasm/go-cosmwasm/issues/29) describes bugs discovered in handling of out-of-gas scenarios (They are never handled correctly, and could cause UB before mitigations that the above PR put in place)
- [x] Adjust `cosmwasm` runtime-to-wasm FFI to allow arbitrary-length buffers
  - Cosmwasm team is going to try doing it themselves again. @reuvenpo helped them find the right approach to implementing this:
  https://github.com/CosmWasm/cosmwasm/pull/245 & https://github.com/CosmWasm/cosmwasm/pull/306
  - Update 2020-05-18: For now this is on hold since this turns out to be nontrivial, and there are other priorities. We expect to return to it though.
  - Update 2020-05-25: work resumed in this PR: https://github.com/CosmWasm/cosmwasm/pull/245
- [x] Port the changes implemented in the cosmwasm repos to our fork

**Comment by reuvenpo** [comment]
the cosmwasm guys now have issues opened about these topics. we will see if they fix it before i do :D

**Comment by assafmo** [comment]
https://github.com/CosmWasm/go-cosmwasm/pull/67

**Comment by reuvenpo** [comment]
This is now pulled in to our repository in #262
