### ISSUE TITLE
Dev-x contributions for incentive program

### ISSUE THREAD

**Issue by ainsleys** [enigmampc/SecretNetwork#145]
@ainsleys and @cankisagun to come up with list for high-value contributor activities that we can support in an incentive program

**Comment by ainsleys** [comment]
- [ ] documentation beta-testing
- [ ] writing tutorials / documentation
- [ ] creating sample smart contracts (similar to gitcoin bounties)
- [ ] creating video walkthrus / tutorials
- [ ] resolving / supporting other devs through dev-help issue tracking
- [ ] creating tooling that might be useful to other developers (templates, etc)

**Comment by ainsleys** [comment]
Can's notes here: https://docs.google.com/document/d/1LEMgmmulq8oCAHSAWBI_-EhZXaHcjPYR3ZHSlp4FWtM/edit

**Comment by cankisagun** [comment]
- [ ] Finalize by end of week of May 15 when we have benchmarks on budget - James
- [ ] Get more detailed information about bounties (lower priority) - Can

**Comment by cankisagun** [comment]
done
