### ISSUE TITLE
Install in Windows doesn't create the config file

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#15]
Gave up after the validate-genesis step, though I might have set it up wrong, who knows. I gave up after trying once and just installed it in WSL instead (though that was also fun)

**Comment by assafmo** [comment]
What guide did you try to do? The full node one?

**Comment by assafmo** [comment]
Also, which config file?

**Comment by assafmo** [comment]
Is this still relevant?

**Comment by Cashmaney** [comment]
didn't test it in ages.. probably? When we get to packaging the new exec we can test it again
