### ISSUE TITLE
Make sure WASM memory usage is explicitly capped

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#153]
In the runtime we're building with `wasmi`, we have to make sure we hook into the event where the vm is requesting additional memory, and cause a Trap (or similar) if it exceeds the limit we set (e.g. 0.5GB).
We must do this because if we don't then a simple malicious contract can try to allocate more memory than is available inside the enclave environment (in one go or multiple allocations). In Rust, Out-Of-Memory is handled by aborting the process, which in our case translates to an easily provokable complete network halt, and we don't want that.

**Comment by assafmo** [comment]
I think there's a hard limit on gas - https://discord.com/channels/669268347736686612/669274997264613376/719110405527568415

**Comment by reuvenpo** [comment]
This was definitely NOT a "good first issue", but over the last couple weeks @assafmo and myself completed this task completely, and we think we correctly defend against OOM events in the enclave now :)
