### ISSUE TITLE
Fix bootstrap trust issues

### ISSUE THREAD

**Issue by guyz** [enigmampc/SecretNetwork#181]
When a bootstrap nodes creates the seed, it needs to prove that:

1. That seed was properly generated inside of the enclave.
2. The seed that's being relayed to other nodes in the future is this same seed.

(2) is trivial (Thanks Tom!) since the bootstrap node creates a private/pubkey that will be used in the key agreement protocol with new nodes. So that limits the bootstrap (and later on other nodes) from running this from anywhere but their enclave.

As to (1), the bootstrap nodes needs to publish the remote attestation certificate to prove their seed/identity keypair were generated inside of the enclave.

Every future node (node 2, 3, ...) should validate this certificate.

Open question: What happens if someone runs a different enclave code and generates a RA that supposedly creates a seed? This should not be possible but we need to check this.

**Comment by reuvenpo** [comment]
>Open question: What happens if someone runs a different enclave code and generates a RA that supposedly creates a seed? This should not be possible but we need to check this.

Isn't this what `MRENCLAVE` is for?
