### ISSUE TITLE
Truffle-like local developer environment for Secret network after full secret contract functioality

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#184]
@assafmo 

Capturing our discussion and feedback from @levackt (and other developers), it's critical that we have a local version of secret network, which allows developers to build secret applications locally cc @guyz. We should account for this in the future sprints

**Comment by assafmo** [comment]
cc @Cashmaney

**Comment by reuvenpo** [comment]
done, long ago :)
https://hub.docker.com/r/enigmampc/secret-network-sw-dev
