### ISSUE TITLE
Secret Voting demo

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#188]
Building a secret contract voting demo for the secret network. We are taking Adi's previous voting contract as a guide and doing the following changes:
- [x] create instances of poll contract on the secret network
- [x] wireframes / dataflow (WIP by @cankisagun )
- [ ] more granular feedback about UX:
- New voting token is not a must, but it would be nice to show it as a way to mint new tokens in the Secret Network. I like the idea that 1 SCRT = 10 voting_tokens
- We can keep the current approach to creating a poll
- Currently User 1 stakes tokens and then creates the poll, maybe it’s better UX to first create the poll / define properties and then cast your vote on it as a user. I am raising this because there may be cases that poll creators are not voting
- Quorum method in this example vs. our blockchain governance are different. In the blockchain governance, we need 50% of yes after abstain votes are taken out. For consistency and to prevent confusion, we may want to replicate the blockchain governance process. This means that we need more explanation on the wireframes. I can try to get to that by the end of the week
- Voting period is a big issue. It would probably need to be defined in time (but actually counted in block height). We will need a user to call a tally function right? From what I know, we can tell block height (time) inside SGX and this will require a trigger. This is a discussion we had around Salad (see this issue). We can use an operator for the time being, but it’s not a clean method

Detailed document with milestones are [here](https://docs.google.com/document/d/1uO7bKC-GFe4AeCc1yxJWJoEC8qp6mdQU_pPhZC601zg/edit)

cc @levackt

**Comment by cankisagun** [comment]
@levackt ,
Based on our discussion today regarding issue #201 , let's have a whitelisted address that can collect the tally in the secret contract as the first iteration. We can then look to improve this maybe through a multi-sig implemented at the contract level

**Comment by FishmanL** [comment]
is this meant to be a naive example or a 'if you do it this way you won't have any security holes' example?

**Comment by cankisagun** [comment]
it's a getting started guide / a developer walkthrough to build a secret contract. Enigma does not provide any guarantees on security holes on application we do not build for production level use. That's the responsibility of the dapp developer

**Comment by FishmanL** [comment]
aight, sounds good

**Comment by jlwaugh** [comment]
Demo: https://levackt.github.io/voting-app

![image](https://user-images.githubusercontent.com/4283694/92310129-571fbb00-ef79-11ea-866b-df6c90ce0f54.png)

Code: https://github.com/levackt/voting-app/tree/secret

**Comment by cankisagun** [comment]
Closing this issue as it has been completed
