### ISSUE TITLE
Document limitations of information provided to secret contracts

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#201]
Ever invocation of `init` or `handle` in a secret contract receives an instance of the `Env` type, which is defined [here](https://github.com/CosmWasm/cosmwasm/blob/1dad720c4dcb2a07a04ffe927b8d8b538320d232/packages/std/src/types.rs#L70-L104): (in cosmwasm 0.8) 

In JSON it'll look like this
```json
{
  "env": {
    "block": {
      "height": 123,
      "time": 123,
      "chain_id": 123
    },
    "message": {
      "sender": "asdf",
      "sent_funds": [{"amount": 123, "denom": "SCRT"}, {...}, {...}]
    },
    "contract": {
      "address": "asdf"
    }
  }
}
```

At the moment we only know how to verify that `env.message.sender`. All the other fields in this structure can not be relied upon because they can be forged by a malicious host (of the enclave).
We should document that so that contract authors know not to depend on them, until we add support for that in the future.

**Comment by assafmo** [comment]
Cc @jlwaugh @cankisagun

**Comment by reuvenpo** [comment]
This has been done by @assafmo as part of his documentation work. Thanks Assaf :)
