### ISSUE TITLE
Parse the fields of env and responses in the enclave based on the appropriate types in cosmwasm_std

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#216]
Today, we just parse these objects as dynamic JSON objects, but instead we can parse them as the types. Branch `#200-generate-signed-contract-id` added copies of these types to the `wasmi-runtime` crate.

**Comment by Cashmaney** [comment]
@reuvenpo this was refactored, so when you have some time take a look to see if you think this is still necessary

**Comment by reuvenpo** [comment]
This has been implemented a couple weeks ago now by @Cashmaney :+1:
