### ISSUE TITLE
User Tx key "wallet"/keystore

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#226]
Currently when sending a tx/query we generate a random private key and save it to a file statically. We would probably want to generate a new key per transaction and save it in a TX_HASH => key structure, or something. 

TBD: decide if we make this password protected, and how that affects the user flow when performing a transaction/query. i.e "enter a password to send this tx" -> "okay now enter a different password to send this tx"?? 
Idea - possible to add a "if the user wants to protect this key let him enter a password" optionally, so it's not too obtrusive

**Comment by assafmo** [comment]
I believe tendermint also just saves private keys as plaintext in json files, we might want to start that way as well for better UX and reevaluate after mainnet

**Comment by guyz** [comment]
If no third part client exists that does this, then best to have one master key encrypted/stored in a file with key derived from a password.

Then, that master key can be used to derive new keys as needed?

**Comment by Cashmaney** [comment]
Just leaving this here so we don't forget - We're talking about the keys used for curve25519 DH, which no cosmos wallet would have native support for, even if that's something we'd want to do

**Comment by assafmo** [comment]
No need for now. We'll just document for end users how to back up this key.
