### ISSUE TITLE
Redelegate command error

### ISSUE THREAD

**Issue by jingjang99** [enigmampc/SecretNetwork#248]
Attempts to use the enigmacli tx staking redelegate command are unsuccessful.

Pasting TX hash into the explorer gives error message: 
Unknown error: redelegation to this validator already in progress; first redelegation to this validator must complete before next redelegation: failed to execute message; message index: 0

Get this same message even if trying to redelegate to a novel validator with whom no previous interaction.

**Comment by Cashmaney** [comment]
I think the errors that you are seeing are measures to prevent against "delegation hopping", where you redelegate a second time, while the first is still immature (not enough time has passed). Though the error message is slightly confusing, and should be documented better (see [here](https://docs.cosmos.network/master/modules/staking/01_state.html#redelegation) and [here](https://blog.cosmos.network/re-delegations-in-the-cosmos-hub-7d2f5ea59f56) for more info)

**Comment by Cashmaney** [comment]
@jingjang99 I'm closing this issue for now - if you see this message again, reopen it and we will look into it further:)
