### ISSUE TITLE
Fill in new features from the new versions of cosmwasm components

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#251]
@reuvenpo Is now working on pulling in the changes from the CosmWasm repos to this repository (PR TBD).
When we open the PR for these features, we will have to implement hooks for all the new features, and adjust the existing hooks to accommodate ABI and API changes.

- [ ] Adjust the parameters passed to the enclave entry-points where necessary.
- [ ] Parse replies from contract functions according to the new format
- [ ] Pass `VmError`s and gas usage from imports back to the enclave and then back to the caller
- [ ] Implement `remove_db`
- [ ] Implement `scan_db`
- [ ] Implement `db_next`
- [ ] Implement `external_query`
- [ ] Adjust `read_db`
- [ ] Adjust `write_db`
- [ ] Adjust `humanize_address`
- [ ] Adjust `canonicalize_address`
- [ ] track gas usage in the enclave just like cosmwsam does it (this also means return `gas_used` from some/all the imports.
- [ ] Add checking of "required features" like they do in `cosmwasm_vm`

**Comment by Cashmaney** [comment]
Split this up into smaller issues
