### ISSUE TITLE
Test & Fix cross-platform Makefile targets

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#266]
We only need to compile `secretcli` cross platform, as `secretd` is no longer supported on OSx/Windows :cry:

Make sure the scripts still work & the new files work on fresh OS installs (and/or document any dependencies we might be missing)

**Comment by assafmo** [comment]
Nothing really changed in the CLI, should still work with `xgo`. :+1:

**Comment by Cashmaney** [comment]
**Famous last words**
