### ISSUE TITLE
Implement query_chain

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#277]
External query allows contracts to call other contracts mid-execution. Not a priority for testnet

- [x] Implement naive `query_chain()`
- [x] Implement stack limit for queries

**Comment by assafmo** [comment]
Need to track "recursion" count or "stack size" because allocating more memory than the enclave has crashes the enclave.
E.g. the enclave has 4 GiB and each call to WASM has 32 MiB, then a chain of 128 calls to external query will crash the enclave.

**Comment by assafmo** [comment]
Also, it's better to pass an argument to the enclave on node startup of how much memory each WASM VM is allowed. If it's hard coded to 512 pages (32 MiB) then increasing it means hard fork + recompiling the enclave. If it's passed down to the enclave this can be changed on-the-fly then a simple param change proposal can do the trick.

**Comment by assafmo** [comment]
- [ ] Implement naive `query_chain()`
- [ ] Add mitigation for the attack where a malicious host can pass a query `msg` to `custom` handle of its own and store the query in its state, thus de-anonymizing the query. The solution is to use HKDF a bit differently for `init`, `handle` and `query`, by passing "init", "handle" or "query" as `info` input for the HKDF. 
- [ ] Implement stack limit for queries

**Comment by assafmo** [comment]
Instead of implementing stack size, test if setting [this](https://github.com/enigmampc/SecretNetwork/blob/2961a7cd362c99a047868f7e6f16c68a68317a04/cosmwasm/packages/wasmi-runtime/Enclave.config.xml#L5) to 1/2KiB solves the issue. E.g. try a minimal sized query and see what's the max depth it reaches. Each one of them allocates 12MiB of memory, so lets say that 10-15 deep is enough?

**Comment by assafmo** [comment]
Used this for "stack limit": https://github.com/apache/incubator-teaclave-sgx-sdk/issues/254
(In practice it handles general OOM inside the enclave, so it's better)
