### ISSUE TITLE
Update contract response handling for 0.9

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#282]
- [x] Fix error parsing (encapsulate everything inside a generic error)
- [x] Fix parsing of errors outside of WASM
- [x] Fix handle parsing
- [x] Fix init parsing
- [x] Fix query parsing
- [x] Fix callbacks parsing
  - [x] exec
  - [x] init

**Comment by reuvenpo** [comment]
All contract entry points (`init`, `handle`, `query`, and the new `migrate`) return a JSON with a known schema. This schema has changed between 0.7 and 0.9.
These types serialize into the relevant JSON structures:
* [`InitResult`](https://github.com/CosmWasm/cosmwasm/blob/b971c037a773bf6a5f5d08a88485113d9b9e8e7b/packages/std/src/init_handle.rs#L129)
* [`HandleResult`](https://github.com/CosmWasm/cosmwasm/blob/b971c037a773bf6a5f5d08a88485113d9b9e8e7b/packages/std/src/init_handle.rs#L153)
* [`MigrateResult`](https://github.com/CosmWasm/cosmwasm/blob/b971c037a773bf6a5f5d08a88485113d9b9e8e7b/packages/std/src/init_handle.rs#L178)
* [`QueryResult`](https://github.com/CosmWasm/cosmwasm/blob/b971c037a773bf6a5f5d08a88485113d9b9e8e7b/packages/std/src/query.rs#L13) - Note that this one is very different.

These links are to a recent version of these types in the CosmWasm repos, a short time before the 0.9 release, but double check their most recent definition when addressing this.

**Comment by Cashmaney** [comment]
This is mostly on the Rust side of things (parsing the structure inside the enclave), but possibly also on the Go side as well
