### ISSUE TITLE
Research solutions for contract migration

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#284]
Look into how we can support contract migrations (upgrading a single contract by the owner). 

This is a function that is supported by CosmWasm, but due to our extra-fun security features it probably won't work out of the box. 

See:
https://github.com/enigmampc/SecretNetwork/blob/ee4e71486b7802e7292c85ac0984474c138ac3ea/cosmwasm/packages/sgx-vm/src/instance.rs#L299

**Comment by assafmo** [comment]
I don't like this feature for us. Contracts admins is the opposite of trustless. I highly doubt we will implement this.
