### ISSUE TITLE
add automatic heartbeat/connection testing to contract execution

### ISSUE THREAD

**Issue by FishmanL** [enigmampc/SecretNetwork#290]
related to my PR -- the best way to prevent replay attacks is probably to require nodes to randomly select peers for heartbeat checks, where the selected peer pings back with 'here's the state of the blockchain and a merkle tree of the last N blocks' to verify that you're not behind and not eclipsed

**Comment by FishmanL** [comment]
you probably need this every time a contract receives input, not sure if you need it every time the contract would emit output

**Comment by assafmo** [comment]
Related: #289

**Comment by Cashmaney** [comment]
Closing this. Opened #308 which include this as a possible solution
