### ISSUE TITLE
what's the point of ad in DB state?

### ISSUE THREAD

**Issue by FishmanL** [enigmampc/SecretNetwork#293]
it looks like it's just a repeated hash of field-name -- but given a successful write, you can just rehash those 32 bytes to generate the next AD, so it doesn't look like it actually correctly protects against malicious overwrites?

**Comment by Cashmaney** [comment]
> The point of the AD is to create different encryption results, not to provide any sort of authentication. While we could have used an implementation like RFC6979, the cost is probably not worth the effort

Discussed in detail here:

https://chat.scrt.network/channel/general?msg=xidvPZnCPFumATyW5
