### ISSUE TITLE
Fix data leakage about secret contract's Error vs. Success?

### ISSUE THREAD

**Issue by assafmo** [enigmampc/SecretNetwork#309]
CosmWasm query/execution receives as a response either:
`{"Ok":"encrypted data"}`
Or:
`{"Err":"encrypted data"}`
Which leaks whether the call was successful or not

**Comment by reuvenpo** [comment]
Just to explain why we closed - This can not be done, otherwise the chain will stop reverting failed contract runs. The solution for contract developers is to return a nested result in the `Ok` variant

**Comment by assafmo** [comment]
But note that if a developer chooses to warp `Error` inside `Ok` for privacy reasons, state changes won't be reverted by the blockchain.
