### ISSUE TITLE
Implement "staking" feature

### ISSUE THREAD

**Issue by assafmo** [enigmampc/SecretNetwork#325]

**Comment by Cashmaney** [comment]
Is this the same as #280?

**Comment by reuvenpo** [comment]
This is actually related to #277 . External query has several types, one of them being contract queries, another one being the staking queries. There is also a banking query (how much funds does an address have) and custom queries (chain-specific queries to custom logic)

**Comment by assafmo** [comment]
Thanks. I don't think this is a lot of work. We probably only need to encrypt the msg of a contract query, and pass the rest as is to the Go code.

**Comment by guyz** [comment]
Why do we need this given that contextual chain data inside of the enclave can't be trusted?

**Comment by reuvenpo** [comment]
Yeah, so we _could_ just call out to the Go side to implement this, but that would mean that the ocalls will have to have full permissions to call back into ecalls, and that we won't be able to trust the results that the Go side returns.
There is an alternative, which is reimplemet some of the dispatch code inside the enclave, and a way of requesting access to the code and storage of a second contract, but this still requires a little bit of design work before it can be done.

**Comment by reuvenpo** [comment]
In the current design, this is a subtask of #277.
CC: @assafmo
