### ISSUE TITLE
Module Idea - Secret Accounts & Secret Payments

### ISSUE THREAD

**Issue by assafmo** [enigmampc/SecretNetwork#33]
Without using contracts, we could extend the Bank and Auth modules to use SGX (like we're extending CosmWasm), thus creating private accounts and payments.

**Comment by ainsleys** [comment]
for my reference and @cankisagun 's the docs for mentioned cosmsdk modules:
auth: https://docs.cosmos.network/master/modules/auth/

bank: https://docs.cosmos.network/master/modules/bank/
