### ISSUE TITLE
Wallet support

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#366]
Secret network requires wallet support to be able to enable the following features:
- [ ] secret contract interaction (cosmwasm.js or secret.js enabled)
- [ ] staking module
- [ ] governance module
- [ ] transactions

The biggest priority right now is secret contract suport. This feature is not supported by any wallets in the Cosmos ecosystem. One way to approach this can be to fork the open source browser extension for Lunie and support secretJS library. Here's the repo for the open source Lunie extension - https://github.com/luniehq/lunie/tree/develop/extension

**Comment by assafmo** [comment]
SecretJS code exmples: https://github.com/enigmampc/SecretHoldEm/blob/master/gui/src/App.js

**Comment by cankisagun** [comment]
keplr to the moon!
