### ISSUE TITLE
Any chance for nondocker based dev/test environments?

### ISSUE THREAD

**Issue by FishmanL** [enigmampc/SecretNetwork#368]
if you give me a zipped filesystem and a build script I'll make it work
docker on windows is hell
pls don't make me suffer thru it

**Comment by assafmo** [comment]
You can try to run `make sanity-test`, or checkout our [ci.yml](https://github.com/enigmampc/SecretNetwork/blob/develop/.github/workflows/ci.yaml) but I'm not sure how compiling SGX on Windows would work.
Docker on WSL is not so bad, though.

**Comment by Cashmaney** [comment]
@FishmanL I use docker with WSL2 on Windows as my main dev machine and it works great. Keep in mind that if you aren't using docker you'll have to install the SGX SDK to get things running anyway, which is no fun on Windows. My recommendation is to either use a Linux VM (and then you can also use docker easily) or WSL2 + docker if you want to keep things simple
