### ISSUE TITLE
Secret JS CLI

### ISSUE THREAD

**Issue by levackt** [enigmampc/SecretNetwork#372]
The [CLI](https://github.com/enigmampc/SecretNetwork/tree/develop/cosmwasm-js/packages/cli) doesn't work for secret contracts yet. 
You can query block height and such, but not contracts which fail with "Thrown: Error: illegal base64 data at input byte 0 (HTTP 500)"

This is expected because I'm not using the Secret JS package, so maybe there's some docs and package config needed to get this working.

**Comment by reuvenpo** [comment]
done a few months ago :)
