### ISSUE TITLE
ERROR: unknown flag: --unsafe-cors

### ISSUE THREAD

**Issue by levackt** [enigmampc/SecretNetwork#374]
Should be able to enable unsafe-cors flag when starting the rest-server, see [cosmos-sdk](https://github.com/cosmos/cosmos-sdk/pull/5671/files)

Should be highlighted this is for dev only, use at own risk.
For longer running environments like integration there's a sample service to [start a rest service](https://github.com/enigmampc/SecretNetwork/blob/master/docs/lcd-server-example.md)

**Comment by assafmo** [comment]
This is solved for now via https://hub.docker.com/r/enigmampc/secret-network-sw-dev

**Comment by assafmo** [comment]
Also might be relevant: https://www.npmjs.com/package/local-cors-proxy
