### ISSUE TITLE
Secret contract getting started guide

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#399]
Getting started guide for developers based on the secret voting demo (issue #188)

Pending secretJS documentation - will be out before Phase 2 Testnet

**Comment by cankisagun** [comment]
Based on 7/31 meeting
- [ ] Finalize the docs (secret contract dev guide on build) by Tuesday
- [ ] Get 2-3 more feedback before the end of week (aug 6)
- [ ] Big mention of updated contract guide with phase 2 testnet push (aug 6-7)
- [ ] Detailed walkthrough (blog post similar to Adi’s) by Aug 18 - based on secret voting (if query is not fixed we will remove quorum from the contract)

**Comment by cankisagun** [comment]
We failed to deliver on the targets above

**Comment by jlwaugh** [comment]
https://build.scrt.network/dev/quickstart.html

https://github.com/enigmampc/SecretNetwork/blob/master/docs/dev/quickstart.md

**Comment by mohammedpatla** [comment]
I am currently doing a video based on this guide, will share more once I have progress. And will keep it in rocket channels.

**Comment by reuvenpo** [comment]
@mohammedpatla Were all the goals of this issue completed? if so, can we close it?

**Comment by mohammedpatla** [comment]
@reuvenpo Yes this issue can be closed.

**Comment by reuvenpo** [comment]
cool, thanks! :muscle:
