### ISSUE TITLE
Web-IDE for secret contracts

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#404]
web-IDE or similar efforts by https://studio.ethereum.org/ or [Near Protocol](https://github.com/nearprotocol/NEARStudio).

**Comment by assafmo** [comment]
I'm no sure this is super-beneficial.
Setting up [vscode](https://code.visualstudio.com/) with the [rust-analyzer extension](https://rust-analyzer.github.io/) is free, lightweight, and takes minutes.
We're not like Ethereum that invented solidity and serpent and didn't have any IDE support.

**Comment by levackt** [comment]
IntelliJ community edition is pretty handy too

**Comment by assafmo** [comment]
https://github.com/enigmampc/SecretNetwork/blob/master/docs/developing-secret-contracts.md#ides
