### ISSUE TITLE
Set gas limit per block

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#426]
Set a gas limit per block. Should limit execution to a few seconds per block at the worst case

**Comment by assafmo** [comment]
Cosmos Hub: 2mn

**Comment by assafmo** [comment]
A simple (read + write to storage) poker tx on testnet cost around 80k.
Send tx cost around 40k. This means on the Cosmos Hub they're limited to 50 tx/block, right? Which roughly translates to 8 tx/sec.

**Comment by Cashmaney** [comment]
The question is how much gas it takes to loop the execution for ~5 seconds

**Comment by assafmo** [comment]
Should be easy to benchmark. We can always start small and enlarge it later. E.g. if tx is 80k gas, then 2mn/block == ~25 tx/block == 4 tx/sec.
Only issue is that to change this parameter requires a hard fork as it's hard coded in `genesis.json` and inaccessible via gov.

**Comment by reuvenpo** [comment]
can this not be made accessible to gov?

**Comment by Cashmaney** [comment]
@reuvenpo we'd have to write a cosmos module for that, which I'm not terribly excited about right now. As this is hard coded in the genesis file I'm going to go ahead and close this for now, and we can revisit in the future
