### ISSUE TITLE
Move ias parameters to Go

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#427]
Instead of having them as compile-time parameters in the enclave, we should move them to compile time parameters on the go side, so we can be more flexible. These parameters are the spid and the api key for the IAS. After moving them there they can be loaded on the enclave during the `init-enclave` stage

**Comment by toml01** [comment]
@Cashmaney Is there anything else you had in mind except for that `spid` and the `api_key`?
