### ISSUE TITLE
Fix `--generate-only` for Compute txs

### ISSUE THREAD

**Issue by toml01** [enigmampc/SecretNetwork#434]
```bash
➜  ~ secretcli tx compute instantiate 1 '<message>' --label test --from <address> --amount 100uscrt --generate-only
Failed to get IO key. Make sure the CLI and the node you are targeting are operating in the same SGX mode
2020/07/29 12:25:58 no RPC client defined
ERROR: no RPC client defined
```

**Comment by Cashmaney** [comment]
Did you have an RPC client defined? We can add a way to pass the IO master cert via parameter so someone can create completely offline transactions, but otherwise if you don't specify --node this is expected behaviour

**Comment by toml01** [comment]
Yep, the command was act an alias for `SGX_MODE=SW secretcli --node tcp://localhost:26657 --chain-id enigma-testnet`

**Comment by Cashmaney** [comment]
😢
