### ISSUE TITLE
Review secret-secret contract

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#486]
Make sure it is compatible with cw-20, clean up the code, optimize what can be optimized etc.

**Comment by reuvenpo** [comment]
See work being done here: https://github.com/enigmampc/secret-secret/pull/6

**Comment by reuvenpo** [comment]
See work being done here: https://github.com/enigmampc/secret-secret/pull/6

**Comment by reuvenpo** [comment]
This issue is now represented by this board:
https://github.com/enigmampc/SecretNetwork/projects/19
