### ISSUE TITLE
Test mainnet upgrade

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#497]
- [x] Bootstrap node can create the genesis master seed and start up the new chain
- [x] Current validators and delegators don't get slashed
- [x] Current validators can register and unjail

**Comment by assafmo** [comment]
https://discord.com/channels/669268347736686612/669274997264613376/738130696144420905

**Comment by assafmo** [comment]
https://gist.github.com/assafmo/631bf61c1f1f8d5b44a4a6b492ee120a

**Comment by assafmo** [comment]
https://github.com/enigmampc/SecretNetwork/releases/tag/v0.2.2

**Comment by assafmo** [comment]
https://discord.com/channels/669268347736686612/669274997264613376/749689664444825610

**Comment by assafmo** [comment]
https://github.com/enigmampc/SecretNetwork/blob/master/docs/upgrade-secret-1-to-secret-2.md
