### ISSUE TITLE
Document secretcli for compute

### ISSUE THREAD

**Issue by assafmo** [enigmampc/SecretNetwork#499]
- [x] In the CLI docs, add docs for `secretcli {q,tx} compute`
- [x] and also how to back up `~/.secretcli/id_tx_io.json`.

Related: #226

**Comment by mohammedpatla** [comment]
Yes,
Documentation on how to retrieve a TX hash of a compute function and other query's to retrieve different types of data.
A lot of commands were shared on rocket chat, i think it would be great to have those in the documentation.

**Comment by assafmo** [comment]
Will be done this week.

**Comment by assafmo** [comment]
https://github.com/enigmampc/SecretNetwork/blob/master/docs/backups.md#client-transaction-encryption-key-for-secret-contracs

**Comment by assafmo** [comment]
@mohammedpatla I think that's a good start: https://github.com/enigmampc/SecretNetwork/blob/master/docs/validators-and-full-nodes/secretcli.md#secret-contracts

Let me know what you think.

**Comment by mohammedpatla** [comment]
@assafmo One command that I would like is to get a list of all contracts made by my address? like @reuvenpo had pointed in rocket chat.

```secretcli q compute list-code | jq '.[] | .id' | xargs -n1 secretcli q compute list-contract-by-code | jq -r 'select(. != null) | .[] | @text ' | grep secret1dla84rxeps38vk8v5eyyrqfs0p0w5l8mrm4sad```

Otherwise, that's good!!

**Comment by assafmo** [comment]
Yeah, I can definitely go down this rabbit hole of one-liners... :joy:
