### ISSUE TITLE
Finish polishing the SNIP-20 specification

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#555]
- compatibility with the secret-secret source code
- full description of input and output types
- make it look nice and organized

EDIT: See https://github.com/SecretFoundation/SNIPs/pull/3

**Comment by assafmo** [comment]
Exact function names for queries, just like it is for handles right now.
Exmpale: [handle](https://github.com/SecretFoundation/SNIPs/blob/614b2028573a84b1eae051a6a77210ad5c01f3de/SNIP-20.md#setviewingkey) & [query](https://github.com/SecretFoundation/SNIPs/blob/614b2028573a84b1eae051a6a77210ad5c01f3de/SNIP-20.md#balance---authenticated)

**Comment by toml01** [comment]
Open questions:
* In SendFrom, should the sender in ReceiveMsg should be the message sender or the tokens owner? (see https://github.com/enigmampc/secret-secret/pull/19)
* Should we enforce 52-byte long passphrases for SetViewingKey?

**Comment by reuvenpo** [comment]
How to do migrations: https://github.com/enigmampc/SecretNetwork/issues/558

**Comment by reuvenpo** [comment]
The SNIP-20 update can be seen in this PR: https://github.com/SecretFoundation/SNIPs/pull/3
Please check it out and give any feedback you may have on it.

**Comment by reuvenpo** [comment]
This has now been completed as SecretFoundation/SNIPs#3 has been merged.
Closing.
