### ISSUE TITLE
Consider feasibility of writing a proxy contract for secret-secret so that we can migrate in case of bugs

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#558]

**Comment by toml01** [comment]
How about a "lazy" approach:
Migrate each account only on an operation related to that account. For example: on the balance query we do (pseudo):
  ```
  query_balance(account) {
    if (!storage.exists(account)) {
      /* query from old contract and save to new contract's state */
    }

    /* normal contract execution */
  }
  ```

Not the prettiest thing in the world but could work

**Comment by reuvenpo** [comment]
Interesting...
That would require a way for the new contract to deanonimize the funds in the old contract. Is there a way to do this cleanly?
We could maybe have a function that only the contract admin can call, that allows them to set an address of the new contract, and then have it so that this new contract is allowed to access all the information that it might want to.
This would require trusting the admin, but you have to trust them anyways.
If we take this direction, I'd at least expose a query (unauthorized) which returns the address of the new contract, if it was set, which would indicate a migration has been started.

**Comment by toml01** [comment]
I think we are okay with the solutions we came up with so far
