### ISSUE TITLE
Document secret-secret specifically

### ISSUE THREAD

**Issue by reuvenpo** [enigmampc/SecretNetwork#559]
This is on top of the SNIP-20 specification. we want to have a description of the specific way secret-secret is implemented, the specific things it does that may be different from the spec or extensions of it, write an integration guide for other contracts

**Comment by toml01** [comment]
* How do I register a `reveive` function (how to integrate with another contract)

**Comment by reuvenpo** [comment]
The secret-secret readme has now been updated with this information. integration with other contract will be described either in the SNIP-20 spec, or in a separate document later.
