### ISSUE TITLE
SecretToken demo

### ISSUE THREAD

**Issue by cankisagun** [enigmampc/SecretNetwork#563]
We want to showcase how SecretToken concept can today be used for transactional privacy and then give a glimpse of what’s possible in the future

The goal is to introduce secretToken concept - secretToken is an ERC20 like fungible token construct that is based on a Secret Contract, which are smart contracts with encrypted inputs, outputs and state. Given the encryption properties of secret contracts (especially inputs and state), secretTokens act as privacy preserving tokens and can be used in privacy preserving applications. 

You can use the script below as a guide or use it as-is

Demo: Today we will demonstrate to you how secertTokens can be minted and used for transactional privacy. Later on, we will be demonstrating the ability to use secretTokens in DeFi applications. Let's see how secretTokens work:
1) Alice has 10 SCRT
2) Alice sends 10 SCRT to Bob - it’s visible can be seen on-chain
3) Minting: Bob mints 10 secretSCRT using the secretToken standard. What happens is 
- Bob sends 10 SCRT to the secretToken minting contract - can be seen on-chain (explorer can be used as a proof)
- Bob receives 10 secretSCRT to his own address (Bob1). This can only be verified / seen by Bob but no one else. 
4) Transfers
- Bob sends 3 secretSCRT to another address controlled by him (Bob2). We can see on the block explorer that Bob is interacting with SecretToken contract but we have no idea in what way. 
- Bob sends 7 secretSCRT to Alice’s address (?). Again we can see on the block explorer that Bon has interacted with the contract but nothing else.
- After the step above, we should show: Bob1 has 0 secretSCRT balance, Bob2 has 3 secretSCRT balance, Alice has 7 secretSCRT balance and these balances are only visible to Bob and Alice respectively
5) Withdrawal
- Bob2 is able to burn 3 secretSCRT and receive 3 SCRT to Bob2. When we look on the blockchain explorer, there’s 3 SCRT going to Bob2 from the contract. We can’t tie it to Bob1. 
- Same with Alice - she burns 7 secretSCRT and receive 7 SCRT. There’s no way to tie Alice to Bob1

Wrap-up: We just demonstrated how to mint a secretToken in the secret network using SCRT. This process is similar to minting wETH using ETH, only if wETH provided users privacy features! We then used the secretSecrets in a simple transactional use-case. The next steps for Secret Network are:
Allow more assets to use the secretToken standards by focusing on bridges
Enable secretTokens to be used in DeFi use-cases such as swaps
Thank you and until next time….

**Comment by WhisperNode** [comment]
Would the ideal video be a walkthrough screen record, or are you looking for something potentially animated like an explainer video?

**Comment by cankisagun** [comment]
screen record

**Comment by mohammedpatla** [comment]
Still working on this @cankisagun.
Hopefully should have some updates by the end of the week.

**Comment by cankisagun** [comment]
Thanks @mohammedpatla - assigning this issue to you :)

**Comment by CarterLWoetzel** [comment]
@cankisagun How would you describe the secret contract that manages a secret-20 token? Is it a essentially the intermediary of all transactions of that specific secret-20 that also manages how said secret-20 tokens interact with other secret contracts? The greater amount of detail that can be provided about how the secret contract mints and manages, and how transactions are recorded by a secret-20, the better I can write an article/mohammed can create a visual for this.

**Comment by mohammedpatla** [comment]
Also linking this in here for reference : https://github.com/enigmampc/SecretNetwork/issues/543

**Comment by WhisperNode** [comment]
> screen record

Not possible to do a screen record if the block explorers and whatnot don't exist right? I had worked up some simple mockups for use.
