### ISSUE TITLE
Create generic bridge interface so we can easily scale to other networks

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#593]
Ideally, we'd want to get to a point where adding a new network would require a few core components to be implemented (e.g. `sign_transaction`, `get_new_transactions`) and everything else would be generic

**Comment by reuvenpo** [comment]
The generic bridge interface has been implemented in this branch: https://github.com/enigmampc/EthereumBridge/pull/13
The branch will continue living as i work on the Cosmos Hub bridge on it.
