### ISSUE TITLE
Add SNIP-20 interfaces to secret toolkit

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#608]
Adding easy ways to interface with SNIP-20 tokens will probably be a helpful building block that we could add to the secret-toolkit. See here: https://github.com/enigmampc/EthereumBridge/blob/master/src/contracts/secret/secret-swap-contract/src/token_messages.rs for an example implementation of some functions.

**Comment by reuvenpo** [comment]
This has been implemented by @baedrik a couple months ago and has been frequently used by everyone since :heart:
