### ISSUE TITLE
Make the `SecretUtils` interface return the pub key asynchronously

### ISSUE THREAD

**Issue by Thunnini** [enigmampc/SecretNetwork#626]
Sorry for the late response.

I looked around the suggestion of the secret utils interface from https://github.com/chainapsis/keplr-extension/issues/36
However, after trying to implement the `SecretUtils` in the extension wallet side, I realized that it is difficult to inject the public key itself to the `SecretUtils` because JS can communicate with the extension only asynchronously due to the fundamental concept of JS.
So, I suggest that `SecretUtils` returns the public key asynchronously such as
```
export interface SecretUtils {
  getPubkey: () => Promise<Uint8Array>;
  decrypt: (ciphertext: Uint8Array, nonce: Uint8Array) => Promise<Uint8Array>;
  encrypt: (contractCodeHash: string, msg: object) => Promise<Uint8Array>;
}
```

**Comment by Cashmaney** [comment]
@Thunnini Check out #630 :)

**Comment by assafmo** [comment]
@Thunnini is this still needed?

**Comment by Thunnini** [comment]
@assafmo This has been resolved. will close the issue.
