### ISSUE TITLE
Fix the Stargate flag hell

### ISSUE THREAD

**Issue by toml01** [enigmampc/SecretNetwork#644]
See if Cosmos/anyone else introduced solutions, or implement ourselves:
* Find a way to keep persistent configurations (a la `config.toml`)
* Fix [this code](https://github.com/enigmampc/SecretNetwork/blob/f23f9c2b1ab36899716dd42ece112570cdbba665/cmd/secretd/root.go#L307-L330)

**Comment by reuvenpo** [comment]
bit of a rumour but i heard from one of the cosmos devs a few weeks ago that they know it's a very requested issue and will prioritize it after the stargate mainnet launches (so... soom :tm

**Comment by reuvenpo** [comment]
This has been implemented in a recent stable release:
https://github.com/cosmos/cosmos-sdk/releases/tag/v0.42.5

**Comment by reuvenpo** [comment]
I'll leave this as open for now - just gotta make sure there's no stray code associated with trying to solve this issue, as indicated by the link @toml01 shared originally
