### ISSUE TITLE
Change Tendermint dependency

### ISSUE THREAD

**Issue by toml01** [enigmampc/SecretNetwork#645]
Currently `go.mod` points to a local clone of tendermint.
Reason:
* We wanted keep support legacy signature validation in the enclave
* To do the above we had to use tendermint's version of `secp256k1`
* The version of `cosmos-sdk` we currently on (v0.40.0-rc1) points to a tendermint version that does not have `secp256k1`
* The version of tendermint that *does* have the mentioned crypto lib is not released yet and does not have certain Version variables that cosmos-sdk uses

Hence -
* Cloned the newer (unreleased) tendermint version locally 
* Added the required missing version indicators

What to do next - 
We will probably won't need tendermint's lib when we update our code to work with the new proto Tx interfaces (instead of the legacy ones). So just take the default tendermint version that the cosmos-sdk needs and you'll probably be fine!

**Comment by reuvenpo** [comment]
Yup, this seems to have been fixed some time after this issue was opened, in [cosmos-sdk v0.40.0-rc5](https://github.com/cosmos/cosmos-sdk/releases/tag/v0.40.0-rc5). (See the second bullet of "Bug Fixes")
