### ISSUE TITLE
Macroify enclave pointer validation

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#656]
All these https://github.com/enigmampc/SecretNetwork/blob/016ed04350a7398836b72fc34dfbdf255008e5f2/cosmwasm/packages/wasmi-runtime/src/exports.rs#L136-L155

Should be prettified into a macro or something

**Comment by reuvenpo** [comment]
@PumpkinSeed You'll find these links useful:
https://doc.rust-lang.org/reference/macros.html
https://danielkeep.github.io/tlborm/book/index.html

**Comment by reuvenpo** [comment]
I forgot to close this issue after @PumpkinSeed completed this task here: https://github.com/enigmampc/SecretNetwork/pull/689
Thanks again for the help! :smile:
