### ISSUE TITLE
What about arm?

### ISSUE THREAD

**Issue by Kwaskoff** [enigmampc/SecretNetwork#678]
I can be your validator, but I need ARM version of secret node
You write requirements Intel Skylake processor and no documentation of building for ARM processors. It's impossible?

**Comment by toml01** [comment]
Hi @Kwaskoff ,
Our nodes require Intel SGX support, since our private computations rely on SGX secure enclaves.
That is why validators have to run on top of a supported Intel processor.

**Comment by Kwaskoff** [comment]
> Hi @Kwaskoff ,
> Our nodes require Intel SGX support, since our private computations rely on SGX secure enclaves.
> That is why validators have to run on top of a supported Intel processor.

May be you have some steps in your roadmap for go out from SGX technology? You know, it's bad for decentralize when you support intel users only
