### ISSUE TITLE
Efficient state serialization

### ISSUE THREAD

**Issue by guyz** [enigmampc/SecretNetwork#72]
There are at least two thing to consider here:

- Choosing a compressed or binary format for serializing state. This shouldn't be too hard.
- State deltas similar to Discovery.  This is hard, may cause things to break, etc..

Implementing either should only come after we're convinced the network load is too much, or gas costs make loading/storing too prohibitive.

**Comment by assafmo** [comment]
Dup with #70?

**Comment by assafmo** [comment]
Closed #70, but whoever gets this should also look at:
- https://forum.enigma.co/t/serialize-format-of-states/1384/2
- https://github.com/confio/cosmwasm/issues/78
