### ISSUE TITLE
failed to get from fields: The specified item could not be found in the keyring

### ISSUE THREAD

**Issue by neocrash** [enigmampc/SecretNetwork#725]
some flags don't working with "secretcli tx staking edit-validator"
-flags : --website, --identity, --details
-error message : failed to get from fields: The specified item could not be found in the keyring

But '--commission-rate', '--moniker' flags are working properly.

**Comment by toml01** [comment]
Hi @neocrash ,
From the error message you shared, seems like you failed to provide the `--from` flag.

**Comment by neocrash** [comment]
@toml01
I provided --from flag and
I got another message without --from flag.
Not this message.
Other flags are working properly.

**Comment by toml01** [comment]
`The specified item could not be found in the keyring` means that the account name you are providing does not exist on your machine.
Can you please recheck? e.g. make sure that `secretcli keys show <account_name>` gives you the account you trying to use.

**Comment by neocrash** [comment]
It seems that some file are deleted on my server.
