### ISSUE TITLE
Fix the Cosmwasm concurrency apphash corruption thing

### ISSUE THREAD

**Issue by Cashmaney** [enigmampc/SecretNetwork#773]
Opening this issue in case we want to keep things as they are - we need to fix the concurrency issue that is causing state corruption/apphash crashes

**Comment by assafmo** [comment]
Seems like a caching issue. From Terra:
![image](https://user-images.githubusercontent.com/22766533/125296535-0f06bd00-e32f-11eb-95ce-8e4eb7c1cccd.png)

**Comment by assafmo** [comment]
See this from Simon: https://github.com/CosmWasm/cosmwasm/issues/844#issuecomment-801958832
